Repository Shopify/quilt, pull requests merged in 2018-07, with the labels that each got.

#166 🎉 [New Package] create @shopify/react-form-state
  README.md
  packages/react-form-state/README.md
  packages/react-form-state/docs/FAQ.md
  packages/react-form-state/docs/building-forms.md
  packages/react-form-state/docs/validators.md
  packages/react-form-state/package.json
  packages/react-form-state/src/FormState.ts
  packages/react-form-state/src/components/List.tsx
  packages/react-form-state/src/components/Nested.tsx
  packages/react-form-state/src/components/index.ts
  packages/react-form-state/src/components/tests/List.test.tsx
  packages/react-form-state/src/components/tests/Nested.test.tsx
  packages/react-form-state/src/components/tests/components/Input.tsx
  packages/react-form-state/src/components/tests/components/index.ts
  packages/react-form-state/src/index.ts
  packages/react-form-state/src/test/FormState.test.tsx
  packages/react-form-state/src/test/array-utilities.test.tsx
  packages/react-form-state/src/test/validators.test.tsx
  packages/react-form-state/src/types.ts
  packages/react-form-state/src/utilities.ts
  packages/react-form-state/src/validators.ts
  packages/react-form-state/tsconfig.json
  yarn.lock
Labels: new package

#200 [react-form-state] Adds support for arrays of validators to validateNested
  packages/react-form-state/src/tests/validators.test.tsx
  packages/react-form-state/src/validators.ts
Labels: bug

#171 🎨 [react-shortcuts] Add better key types
  packages/react-shortcuts/src/Shortcut/Shortcut.tsx
  packages/react-shortcuts/src/ShortcutManager/ShortcutManager.tsx
  packages/react-shortcuts/src/index.ts
  packages/react-shortcuts/src/keys.ts
  packages/react-shortcuts/src/tests/ShortcutManager.test.tsx
  packages/react-shortcuts/src/types.ts
  packages/react-shortcuts/tsconfig.json
Labels: polish
