Repository Shopify/quilt, pull requests merged in 2020-03, with the labels that each got.

#1309 [react-form] useList list as arg
  packages/react-form/CHANGELOG.md
  packages/react-form/src/hooks/list/list.ts
  packages/react-form/src/hooks/list/test/list.test.tsx
Labels: Type: Bug 🐛

#1241 Introduce `useInterval` React Hook
  packages/react-hooks/CHANGELOG.md
  packages/react-hooks/README.md
  packages/react-hooks/src/hooks/index.ts
  packages/react-hooks/src/hooks/interval.ts
  packages/react-hooks/src/hooks/tests/interval.test.tsx
Labels: Package: react-hooks, Type: Enhancement 📈

#1312 Solve a potential security vulnerability
  README.md
  packages/react-form-state/package.json
  packages/react-google-analytics/CHANGELOG.md
  packages/react-google-analytics/package.json
  packages/react-google-analytics/tsconfig.json
  packages/react-html/CHANGELOG.md
  packages/react-html/package.json
  packages/react-html/src/server/components/Serialize.tsx
  packages/react-html/src/server/components/tests/Serialize.test.tsx
  packages/react-i18n/README.md
  packages/react-serialize/CHANGELOG.md
  packages/react-serialize/package.json
  packages/react-serialize/src/Serializer.tsx
  packages/react-serialize/src/index.ts
  packages/react-serialize/src/tests/Serializer.test.tsx
  packages/react-serialize/src/tests/utilities.test.ts
  packages/react-serialize/src/utilities.ts
  packages/react-serialize/tsconfig.json
  packages/react-server/package.json
  packages/tsconfig.json
  yarn.lock
Labels: dependencies
